### PR TITLE
Empty metadata should not assign an empty tag.

### LINKED ISSUE #247: XML Generation has empty tag on empty metadata
Empty values in the metadata are creating empty tags in the XML.

i.e.
``` xml
  <AlternateSeries />
  <AlternateNumber />
  <StoryArc />
'''

### PR DESCRIPTION
**Pull request by MichaelFitzurka**
Fixes #247.

### CODE REVIEW

**Comment by lordwelch** [comment]
Can I have you run `make CI` or run black and isort manually?
I plan on having Github Actions report on it automatically but still need to fix a few issues.

**Comment by lordwelch** [comment]
You may need to run `pip install -r requirements_dev.txt` first

**Comment by MichaelFitzurka** [comment]
I did the pip install before making the changes - the code changes were still necessary to fix the issues.
Don't know what you mean by "black and isort".

**Comment by MichaelFitzurka** [comment]
It looks like my last 3 branches got joined together in this commit. :-/

**Comment by lordwelch** [comment]
[black](https://github.com/psf/black) and [isort](https://github.com/pycqa/isort).
They are just tools to ensure that formatting is consistent.
`make CI` will run them automatically

**Comment by MichaelFitzurka** [comment]
I'll make sure to run make in the future.

**Pull request merged**
