### PR TITLE
Feature/add appimage support

### PR DESCRIPTION
**Pull request by bmfrosty**
Changes:
* Added the libfuse2 linux dependency that is required by AppImage
* Added additional files needed to build the AppImage
* Updated the makefile to install appimagetool
* Added command to build the appimage
* Updated build.yaml to also upload .AppImage files

### CODE REVIEW

**Comment by lordwelch** [comment]
I have a few things I want changed
- Remove the -m from zip (that's the flag that deletes files) so that the PyInstaller build can be re-used for the appimage
- Add dist as a dependency for appimage `appimage:` to `appimage: dist` and remove the PyInstaller command in the appimage target
- Copy 'cp -a' the dist/comictagger folder to build/appimage (I don't want to modify build files in-place, and the folder name does not matter to the result in this case)
- You want to use the [latest release] for the appimage tool not the continuous build which goes off of the latest git commit.
- Instead of making an AppRun script create a symlink to comictagger
- Instead of creating an AppRun.desktop use desktop-integration/linux/ComicTagger.desktop as a template e.g. `sed -e 's|/usr/local/share/comictagger/app.png|app|g' -e 's|%%CTSCRIPT%% %F|./comictagger|g'`

If you could also [squash your commits] and force-push to your branch to make this a single change that would be appreciated.

[latest release]: https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
[squash your commits]: https://stackoverflow.com/a/5201642

**Comment by bmfrosty** [comment]
That's all seems reasonable.    

Only one I'm wary of is the .destop file as appimagetool is a bit picky.  I'll find out.

I'm going to close the PR, do all my work in my own fork.

**Comment by bmfrosty** [comment]
reopening and then catching my changes before I squash.  I'm *so good* at screwing up manual squashes.

**Comment by bmfrosty** [comment]
Squashed.

**Pull request merged**
